new iterate.py script called iterate_nojobs.py, but strange logging behavior
SPIDERCMB/xfaster pull request #31
Opened 2023-10-24 21:55 UTC by sGourapura

2023-10-27 13:23 UTC, arahlin requested changes
This script is just the same as iterate.py with small changes to the way run_xfaster is called?  If so, just make the changes as an option in the original iterate.py script, otherwise it's hard to follow what you've actually changed.

2023-10-27 15:41 UTC, arahlin requested changes
A couple of diff-minimizing code change suggestions.  You can batch-commit them from the web interface by going to the "Files Changed" tab on this PR and clicking on "Add suggestion to batch" for each one that you're ok with, then committing all of them at once.

2023-10-27 15:41 UTC, arahlin commented on scripts/gcorr/iterate.py
> +    )
```suggestion
cmd = "python run_xfaster.py --gcorr-config {g} --omp 1 --check-point transfer --reload-gcorr {s} -o {o} > /dev/null".format(
    g=args.gcorr_config, o=run_name_iter, s="--no-submit" if args.no_submit else ""
)
```

2023-10-27 15:41 UTC, arahlin commented on scripts/gcorr/iterate.py
> +    )
```suggestion
cmd = "python run_xfaster.py --gcorr-config {g} --omp 1 --check-point bandpowers -o {o} -f 1 -n {n} {s} > /dev/null".format(
    g=args.gcorr_config, o=run_name_iter, n=int(g_cfg["gcorr_opts"]["nsim"]) - 1, s="--no-submit" if args.no_submit else ""
)
```

2023-10-27 15:41 UTC, arahlin commented on scripts/gcorr/iterate.py
> +if args.no_submit:
Minimize diff
```suggestion
while not np.all(list(transfer_exists.values())):
    # wait until transfer functions are done to submit rest of jobs
```

2023-10-27 15:41 UTC, arahlin commented on scripts/gcorr/iterate.py
> +
```suggestion
    print("transfer exists: ", transfer_exists)
    if args.no_submit:
        if np.all(list(transfer_exists.values())):
            break
        raise RuntimeError("Some/all transfer functions not made: {}".format(transfer_exists))
    else:
        time.sleep(15)
```

2023-10-27 15:50 UTC, sGourapura reviewed
Works for me. Neat this can be done in the gitweb

2023-10-27 15:54 UTC, sGourapura commented
Is there no pushing because we are editing the remote copy directly?

2023-10-27 15:55 UTC, arahlin commented
> Is there no pushing because we are editing the remote copy directly?

That's right.  You can pull these changes in to your checked out copy on your computer with a regular `git pull`.

2023-11-20 21:26 UTC, arahlin approved these changes

2023-11-20 21:27 UTC, merged